---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 1024
    cpus: 1

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

driver:
  network:
  - ["forwarded_port", { guest: 4440, host: 4440 }]

suites:
  - name: default
    run_list:
      - recipe[balanced-rundeck::balanced]
    attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    data_bags_path: "test/data_bags"
